# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: editor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65\x64itor.proto\x12\x06\x65\x64itor\"/\n\rInsertRequest\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\";\n\rDeleteRequest\x12\x15\n\rstartPosition\x18\x01 \x01(\x05\x12\x13\n\x0b\x65ndPosition\x18\x02 \x01(\x05\"\x1f\n\x0c\x45\x64itResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x0e\n\x0c\x46\x65tchRequest\"\x1d\n\rFetchResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"6\n\x05Piece\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0e\n\x06length\x18\x03 \x01(\x05\"c\n\x17SerializedDocumentState\x12\x16\n\x0eoriginalBuffer\x18\x01 \x01(\t\x12\x11\n\taddBuffer\x18\x02 \x01(\t\x12\x1d\n\x06pieces\x18\x03 \x03(\x0b\x32\r.editor.Piece2\x92\x02\n\rEditorService\x12\x39\n\nInsertText\x12\x15.editor.InsertRequest\x1a\x14.editor.EditResponse\x12\x39\n\nDeleteText\x12\x15.editor.DeleteRequest\x1a\x14.editor.EditResponse\x12<\n\rFetchDocument\x12\x14.editor.FetchRequest\x1a\x15.editor.FetchResponse\x12M\n\x14\x46\x65tchSerializedState\x12\x14.editor.FetchRequest\x1a\x1f.editor.SerializedDocumentStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'editor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INSERTREQUEST']._serialized_start=24
  _globals['_INSERTREQUEST']._serialized_end=71
  _globals['_DELETEREQUEST']._serialized_start=73
  _globals['_DELETEREQUEST']._serialized_end=132
  _globals['_EDITRESPONSE']._serialized_start=134
  _globals['_EDITRESPONSE']._serialized_end=165
  _globals['_FETCHREQUEST']._serialized_start=167
  _globals['_FETCHREQUEST']._serialized_end=181
  _globals['_FETCHRESPONSE']._serialized_start=183
  _globals['_FETCHRESPONSE']._serialized_end=212
  _globals['_PIECE']._serialized_start=214
  _globals['_PIECE']._serialized_end=268
  _globals['_SERIALIZEDDOCUMENTSTATE']._serialized_start=270
  _globals['_SERIALIZEDDOCUMENTSTATE']._serialized_end=369
  _globals['_EDITORSERVICE']._serialized_start=372
  _globals['_EDITORSERVICE']._serialized_end=646
# @@protoc_insertion_point(module_scope)
